/*TRAER LA FACTUIRA DE VALOR MAXIMO
QUE HAYA TENIDO EN SUS ITEMS VENDIDOS EL PRODUCOT 256*/
SELECT MAX(Ventas_Total) AS 'Valor Maximo'
FROM ventas
	JOIN ventas_detalle ON VD_VentasId = Ventas_ID
WHERE VD_ProdID=656