#cUANTAS PELICULAS CON RATING PG-13 QUE HAY EN EL STORE NRO2
#HA ALQUILADO EL MEJOR CLIENTE DE TODOS ??
SELECT r.customer_id
FROM rental r
GROUP BY r.customer_id
ORDER BY COUNT(r.customer_id) DESC
LIMIT 1
